// <auto-generated />
using System;
using AddonCraft.Domain.Enums;
using AddonCraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddonCraft.CommandLineInterface.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210317145502_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AddonCraft.Domain.Entities.Addon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<GameFlavor.GameFlavorEnum>("GameFlavor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MetadataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ReleaseType.ReleaseTypeEnum>("ReleaseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.HasIndex("Id", "GameFlavor", "ReleaseType")
                        .IsUnique();

                    b.HasIndex("Name", "GameFlavor", "ReleaseType")
                        .IsUnique();

                    b.ToTable("Addons");
                });

            modelBuilder.Entity("AddonCraft.Domain.Entities.Metadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("AddonCraft.Domain.Entities.Addon", b =>
                {
                    b.HasOne("AddonCraft.Domain.Entities.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.OwnsMany("AddonCraft.Domain.ValueObjects.Module", "Modules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("AddonId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("AddonId");

                            b1.ToTable("Modules");

                            b1.WithOwner()
                                .HasForeignKey("AddonId");
                        });

                    b.Navigation("Metadata");

                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
